version = 1

test_patterns = ["test/**"]

exclude_patterns = ["dist/*min.js"]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "javascript"
enabled = true