version = 1

test_patterns = ["test/**"]

exclude_patterns = ["dist/*min.js"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/QuackatronHQ/Megarepo"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "javascript"

[[transformers]]
name = "prettier"